# Method parameters
linreg:
  penalty: ["elastic_net", "sqrt_lasso", Null]

cart:
  max_depth: [5, 15, Null]
  min_samples_split: [2, 5, 20]
  min_samples_leaf: [1, 5, 10]
  max_features: [Null, 'sqrt']

hie:
  treatment_interaction_degree: [1,2,3]
  outcome_interaction_degree: [1,2,3]

xgboost:
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7, 9]
  subsample: [0.5, 0.7, 1.0]
  min_child_weight: [1, 3, 5]
  gamma: [0, 0.1, 0.2]
  colsample_bytree: [0.3, 0.5, 0.7]

mlp:
  learning_rate: [0.0001, 0.001]
  batch_size: [64, 128]
  num_steps: [5000]
  num_layers: [2]
  hidden_size: [32, 48]

drnet:
  learning_rate: [0.0001, 0.001]
  batch_size: [64, 128]
  num_steps: [5000]
  hidden_size: [32, 48]
  num_bins: [5,10]

vcnet:
  learning_rate: [0.001, 0.01]
  batch_size: [128, 256]
  num_steps: [5000]
  hidden_size: [32]

cbrnet:
  learning_rate: [ 0.001, 0.01]
  batch_size: [64, 128]
  num_steps: [5000]
  hidden_size: [32, 48]
  num_cluster: [5]
  regularization_ipm: [0.001, 0.01, 0.1]
